apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-depl
  labels:
    app: mongo-express-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express-depl
  template:
      metadata:
        name: mongo-express-pod
        labels:
          app: mongo-express-depl
      spec:
        containers:
          - name: mongo-express
            image: mongo-express
            ports:
              - containerPort: 8081
            env:
              - name: ME_CONFIG_MONGODB_ADMINUSERNAME
                valueFrom:
                  secretKeyRef:
                    name: mongo-scrt
                    key: mongo-username
              - name: ME_CONFIG_MONGODB_ADMINPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mongo-scrt
                    key: mongo-password
              - name: ME_CONFIG_MONGODB_SERVER
                valueFrom:
                  configMapKeyRef:
                    name: mongo-config
                    key: database_url
---

apiVersion: v1
kind: Service
metadata: 
  name: mongo-express-srv
spec:
  selector:
     app: mongo-express-depl
  type: LoadBalancer
  ports:
    - name: mongo-express
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000